# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: alfredoizjr/redcon1-auth
        # env:
        #   - name: MONGO_URI
        #     value: 'mongodb://products-mongo-srv:27017/auth'
        #   - name: JWT_KEY
        #     valueFrom:
        #       secretKeyRef:
        #           name: jwt-secret
        #           key: JWT_KEY

# service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
