name: deploy-manifests

on: 
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.GIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save myshop
      - run: kubectl apply -f k8s/
      - run: kubectl apply -f k8s/prod
