name: deploy-costumers

on: 
  push:
    branches:
      - main
    paths:
      - 'costumers/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd costumers && docker build -t alfredoizjr/redcon1-costumers .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD:  ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push alfredoizjr/redcon1-costumers